feat: add network plugin
ignite/apps pull request #19
Opened 2023-10-15 22:30 UTC by Pantani

2023-11-09 01:21 UTC, ilgooz requested changes
Thanks for pushing this!

Meanwhile, we should make it clear that this code originates from [another repo](https://github.com/ignite/cli-plugin-network) and should give attributions to the other authors.

We should try finding the best way of giving attributions; at very least we can include them as [co-authors](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) buy pushing an empty commit. And in the description of the commit we could add more information.

2024-11-08 12:31 UTC, julienrbrt commented on network/CHANGELOG.md
It will be tagged as 0.3.0 right: https://github.com/ignite/cli/pull/4396 ?

2024-11-11 19:59 UTC, Pantani commented on network/CHANGELOG.md
yes!!

2025-03-25 20:54 UTC, julienrbrt submitted a review, later dismissed
utACK. Can we add this to the app registry?

2025-03-26 06:09 UTC, julienrbrt submitted a review, later dismissed

2025-04-02 07:27 UTC, julienrbrt approved these changes

2025-04-02 07:28 UTC, merged