chore: fix `go.work` file and run `make format`
ignite/apps pull request #54
Opened 2024-02-01 19:37 UTC by Pantani

2024-02-01 22:11 UTC, julienrbrt requested changes
The go.work and go.work.sum shouldn't be committed.

2024-02-02 08:31 UTC, jeronimoalbi commented on go.work
Why do we want to commit `go.work` instead of `go.work.example`?

2024-02-02 17:11 UTC, Pantani commented
We agree to not commit the `go.work.sum`. But why do we not commit to `go.work`?

2024-02-02 17:16 UTC, julienrbrt commented
> @jeronimoalbi , @julienrbrt . We agree to not commit the `go.work.sum`. But why do we not commit to `go.work`?
> 
> 
> 
> And why keep the `go.work.example` if we are not using it?

go.work makes it easy for local development but it's going to make unclear what versions uses a program when tagging it (as the tagged version should depend on tagged version - like you should tag something that depends on local replaces)

Keeping a go.work.example is handy for anyone using go.work, but when they submit a PR to the repo they need to make sure they only use released version, or split the PR.

There's a lengthy discussion about this in the SDK somewhere.

2024-02-02 18:52 UTC, Ehsan-saradar commented
Yep, @julienrbrt is right. This is also the case with [ibc-go](https://github.com/cosmos/ibc-go) repository.

2024-02-07 14:28 UTC, closed without merging